### ISSUE TITLE
[Bug]: Incorrect typing in TransformableInfo.message

### ISSUE THREAD

**Issue by mazamachi** [winstonjs/logform#172]
### The problem

Current typing of `TransformableInfo` is
```ts
export interface TransformableInfo {
  level: string;
  message: string;
  [key: string]: any;
}
```
https://github.com/winstonjs/logform/blob/0062e4388c63a037bf469f9d6afbffeba76d5590/index.d.ts#L7-L11

However, `message` property can be non-string object in winston.
https://github.com/winstonjs/winston/blob/master/lib/winston/logger.js#L221-L227

Winston declares message as `any` in TypeScript. 
https://github.com/winstonjs/winston/blob/master/index.d.ts#L81

So the message of `TransformableInfo.message` should be more loose, e.g. `any`.

#### Example
This is problematic when writing custom format function. Like
```ts
const winston = require('winston');
const logger = winston.createLogger({
    level: 'info',
    format: winston.format.combine(
        winston.format((info) => ({
            ...info,
            message: info.message.trim(), // compiles as the `message` type is `string`, but actually it can be `object` or `any`.
        }))(),
        winston.format.simple(),
    ),
    transports: [new winston.transports.Console()],
});
logger.info('      message\t'); // OK. logs `'info: message'`
logger.info({ foo: 'bar' }); // NG. throws error
// Uncaught TypeError: info.message.trim is not a function
//     at Format.transform (...)
//     at Format.transform (/.../node_modules/logform/combine.js:20:24)
//     at DerivedLogger._transform (/.../node_modules/winston/lib/winston/logger.js:313:29)
```

And if a user transforms object properly, typescript cannot compile.
```ts
const winston = require('winston');
const logger = winston.createLogger({
    level: 'info',
    format: winston.format.combine(
        winston.format((info) => ({
            ...info,
            message: typeof info.message === 'string' ? 
                info.message.trim() 
                : info.message.toString(),
                // ^^^ info.message is `never` here, so toString() does not exist
        }))(),
        winston.format.simple(),
    ),
    transports: [new winston.transports.Console()],
});
logger.info('      message\t'); // works. logs `'info: message'`
logger.info({ foo: 'bar' }); // works. logs `'info: [object Object]'`
```
Actually, the example code above cannot be compiled in TypeScript, it can run properly as JavaScript.

### What version of Logform presents the issue?

2.4.0

### What version of Node are you using?

v14.17.0

### Minimum Working Example
(Same as examples above)
```ts
const winston = require('winston');
const logger = winston.createLogger({
    level: 'info',
    format: winston.format.combine(
        winston.format((info) => ({
            ...info,
            message: info.message.trim(),
        }))(),
        winston.format.simple(),
    ),
    transports: [new winston.transports.Console()],
});
logger.info('      message\t'); // OK. logs `'info: message'`
logger.info({ foo: 'bar' }); // NG. throws error
// Uncaught TypeError: info.message.trim is not a function
//     at Format.transform (...)
//     at Format.transform (/.../node_modules/logform/combine.js:20:24)
//     at DerivedLogger._transform (/.../node_modules/winston/lib/winston/logger.js:313:29)
```

```ts
const winston = require('winston');
const logger = winston.createLogger({
    level: 'info',
    format: winston.format.combine(
        winston.format((info) => ({
            ...info,
            message: typeof info.message === 'string' ? 
                info.message.trim() 
                : info.message.toString(),
                // ^^^ info.message is `never` here, so toString() does not exist
        }))(),
        winston.format.simple(),
    ),
    transports: [new winston.transports.Console()],
});
logger.info('      message\t'); // works. logs `'info: message'`
logger.info({ foo: 'bar' }); // works. logs `'info: [object Object]'`
```

### 🔎 Search Terms

typescript, message, typing

**Comment by gregbair** [comment]
Will do
