### ISSUE TITLE
Typescript warning in logform/index.d.ts: "use --declaration --outDir"

### ISSUE THREAD

**Issue by aneilbaboo** [winstonjs/logform#19]
I'm seeing this warning while importing `winston`. (With typescript 2.6.2).

```shell
WARNING in ./node_modules/logform/index.d.ts
Module build failed: Error: Typescript emitted no output for /Users/aneil/code/myapp/web/app-backend/node_modules/logform/index.d.ts.
You should not need to recompile .ts files in node_modules.
Please contact the package author to advise them to use --declaration --outDir.
More https://github.com/Microsoft/TypeScript/issues/12358
    at successLoader (/Users/aneil/code/myapp/web/app-backend/node_modules/ts-loader/dist/index.js:47:15)
    at Object.loader (/Users/aneil/code/myapp/web/app-backend/node_modules/ts-loader/dist/index.js:29:12)
 @ ./node_modules/logform ^\.\/.*$
 @ ./node_modules/logform/index.js
 @ ./node_modules/winston/lib/winston.js
 @ ./src/logger.ts
```

```javascript
// src/logger.ts

const winston =  require('winston');

export const log = winston.createLogger({
  transports: [
    new winston.transports.Console(),
  ]
});
```

**Comment by DABH** [comment]
@aneilbaboo Thanks for reporting!  Check out https://github.com/winstonjs/logform/pull/21 -- this should help (`--noEmit` in particular).  Any chance if you can grab `logform` from my branch and see if it fixes your issue?

**Comment by DABH** [comment]
I'm going to go ahead and merge #21 .  Feel free to follow up if you still have similar errors.  Note that the fixes won't be pushed to NPM likely until Friday.  Thanks!

**Comment by aneilbaboo** [comment]
Hi @DABH - Sorry, I completely missed your message from 14 days ago. For some reason, I didn't get notifications until just now.
