### ISSUE TITLE
[Bug]: Breaking change from safe-stable-stringify package

### ISSUE THREAD

**Issue by SEI-tswokowski** [winstonjs/logform#209]
### The problem

I noticed that Logform is now giving me a syntax error and I believe it is because of a recent problem with safe-stable-stringify.

Two days ago, they updated the version to 2.4.0 via this commit:
https://github.com/BridgeAR/safe-stable-stringify/commit/f001e74a77e64a486b540a6628e39fc21918eb14

Line 215 of this file is now giving me a syntax error:
https://github.com/BridgeAR/safe-stable-stringify/blob/f001e74a77e64a486b540a6628e39fc21918eb14/index.js

This version of the package is working:
"safe-stable-stringify": "2.3.1"

### What version of Logform presents the issue?

2.4.2

### What version of Node are you using?

11,7.0

### If this worked in a previous version of Logform, which was it?

2.4.2

### 🔎 Search Terms

safe stable stringify

**Comment by SEI-tswokowski** [comment]
Here is the error:

13:06:55,632 WARN - /opt/DXBuild/dev/2022_SP11/theme/common/node_modules/safe-stable-stringify/index.js:215
13:06:55,632 WARN - options = { ...options }
13:06:55,632 WARN - ^^^
13:06:55,632 WARN - SyntaxError: Unexpected token ...
13:06:55,632 WARN - at createScript (vm.js:53:10)
13:06:55,632 WARN - at Object.runInThisContext (vm.js:95:10)
13:06:55,632 WARN - at Module._compile (module.js:543:28)
13:06:55,632 WARN - at Object.Module._extensions..js (module.js:580:10)
13:06:55,632 WARN - at Module.load (module.js:488:32)
13:06:55,632 WARN - at tryModuleLoad (module.js:447:12)
13:06:55,632 WARN - at Function.Module._load (module.js:439:3)
13:06:55,632 WARN - at Module.require (module.js:498:17)
13:06:55,632 WARN - at require (internal/module.js:20:19)
13:06:55,632 WARN - at Object. (/opt/DXBuild/dev/2022_SP11/theme/common/node_modules/logform/json.js:5:19)

**Comment by amirhosseinkabiri** [comment]
I had the same error and it was just because of node.js version. installing node.js using yum is wrong! cause it installs the 6.x version. I followed the second method of [this link](https://linuxgenie.net/how-to-install-node-js-on-centos-8/) and everything works.
