### ISSUE TITLE
[Bug]: Error formatter not working as shown in README example

### ISSUE THREAD

**Issue by NazCodeland** [winstonjs/logform#238]
### The problem

I tried using the example shown in the README for the Error Format and I get this error:
```javascript
module.exports = format((einfo, { stack }) => {
                                  ^

TypeError: Cannot destructure property 'stack' of 'undefined' as it is undefined.
    at Format.transform (C:\projectDirecotry\node_modules\logform\errors.js:14:35)
    at Object.<anonymous> (C:\projectDirectory\app.js:6:27)
    at Module._compile (node:internal/modules/cjs/loader:1205:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1259:10)
    at Module.load (node:internal/modules/cjs/loader:1068:32)
    at Module._load (node:internal/modules/cjs/loader:909:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
    at node:internal/main/run_main_module:23:47

Node.js v19.1.0```


### What version of Logform presents the issue?

2.4.2

### What version of Node are you using?

19.1.0

### If this worked in a previous version of Logform, which was it?

_No response_

### Minimum Working Example

```javascript
const { format } = require('logform');
const { errors } = format;

const errorsFormat = errors({ stack: true })

const info = errorsFormat.transform(new Error('Oh no!'));

console.log(info);
// Error: Oh no!
//     at repl:1:13
//     at ContextifyScript.Script.runInThisContext (vm.js:50:33)
//     at REPLServer.defaultEval (repl.js:240:29)
//     at bound (domain.js:301:14)
//     at REPLServer.runBound [as eval] (domain.js:314:12)
//     at REPLServer.onLine (repl.js:468:10)
//     at emitOne (events.js:121:20)
//     at REPLServer.emit (events.js:211:7)
//     at REPLServer.Interface._onLine (readline.js:282:10)
//     at REPLServer.Interface._line (readline.js:631:8)```

### Additional information

_No response_

### 🔎 Search Terms

Error Formatter

**Comment by wbt** [comment]
I'm a little confused here: does the comment show what you actually see? Is that different than what you expect?

**Comment by NazCodeland** [comment]
The code block in "The problem" section is the error that I am getting when I try to run the code given for the Error Formatter in the README, which I copy and pasted in the "Minimum Working Example" section. Hope that answers your question.

**Comment by tom-wild-moose** [comment]
Ran into the same issue.
We ended up having to pass the error object _twice_ (as both "info" and "opts"), i.e. `errorsFormat.transform(error, error)`.
Pretty bizarre, but seems to work:

**Comment by hugo-daclon** [comment]
Got the same issue, I also saw a lot of related issues (#77 #80 #238). 

For me I checked the logging functions (`Logger.error`, `Logger.info`...) and found out we could pass an `infoObject: object` as the parameter, it looks like, though I'm not sure, its type should be a `Partial<TransformableInfo>`. As such, passing a `{ message: myError }` object as the param seems to work just fine : 

```ts
import { config, createLogger, format, transports } from 'winston'
createLogger({
  levels: config.syslog.levels,
  level: 'debug',
  transports: new transports.Console({
    format: format.combine(
      format.errors({ stack: true }),
      format.printf((info) => {
        console.log(info)
        return ''
      })
    ),
  }),
})

const critError = new Error('critError', { cause: new Error('cause') })

logger.crit('Critical error happened:', critError)
logger.crit('Critical error happened:', { error: critError })
logger.crit({ message: critError })
logger.crit(critError)
logger.log('info', critError)
```

Here are the results without commenting the `format.errrors({ stack: true }),` line:

```js
{
  level: 'crit',
  message: 'Critical error happened: critError',
  stack: 'Error: critError\n' +
    '    at <anonymous> (/workspace/src/shared/logger.ts:62:19)\n' +
    '    at ModuleJob.run (node:internal/modules/esm/module_job:329:25)\n' +
    '    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:644:26)\n' +
    '    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:117:5)',
  cause: Error: cause
      at <anonymous> (/workspace/src/shared/logger.ts:62:51)
      at ModuleJob.run (node:internal/modules/esm/module_job:329:25)
      at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:644:26)
      at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:117:5),
  [Symbol(level)]: 'crit',
  [Symbol(splat)]: [
    Error: critError
        at <anonymous> (/workspace/src/shared/logger.ts:62:19)
        at ModuleJob.run (node:internal/modules/esm/module_job:329:25)
        at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:644:26)
        at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:117:5) {
      [cause]: Error: cause
          at <anonymous> (/workspace/src/shared/logger.ts:62:51)
          at ModuleJob.run (node:internal/modules/esm/module_job:329:25)
          at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:644:26)
          at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:117:5)
    }
  ],
  [Symbol(message)]: '{"cause":{},"level":"crit","message":"Critical error happened: critError","stack":"Error: critError\\n    at <anonymous> (/workspace/src/shared/logger.ts:62:19)\\n    at ModuleJob.run (node:internal/modules/esm/module_job:329:25)\\n    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:644:26)\\n    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:117:5)"}'
}

{
  error: Error: critError
      at <anonymous> (/workspace/src/shared/logger.ts:62:19)
      at ModuleJob.run (node:internal/modules/esm/module_job:329:25)
      at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:644:26)
      at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:117:5) {
    [cause]: Error: cause
        at <anonymous> (/workspace/src/shared/logger.ts:62:51)
        at ModuleJob.run (node:internal/modules/esm/module_job:329:25)
        at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:644:26)
        at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:117:5)
  },
  level: 'crit',
  message: 'Critical error happened:',
  [Symbol(level)]: 'crit',
  [Symbol(splat)]: [ { error: [Error] } ],
  [Symbol(message)]: '{"error":{},"level":"crit","message":"Critical error happened:"}'
}

{
  message: 'critError',
  level: 'crit',
  stack: 'Error: critError\n' +
    '    at <anonymous> (/workspace/src/shared/logger.ts:62:19)\n' +
    '    at ModuleJob.run (node:internal/modules/esm/module_job:329:25)\n' +
    '    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:644:26)\n' +
    '    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:117:5)',
  [Symbol(level)]: 'crit',
  [Symbol(message)]: 'critError'
}

{
  level: 'crit',
  [Symbol(level)]: 'crit',
  [Symbol(message)]: '{"level":"crit"}'
}

{
  level: 'crit',
  [Symbol(level)]: 'crit',
  [Symbol(message)]: '{"level":"crit"}'
}
```
And with the line commented :
```js
{
  level: 'crit',
  message: 'Critical error happened: critError',
  stack: 'Error: critError\n' +
    '    at <anonymous> (/workspace/src/shared/logger.ts:62:19)\n' +
    '    at ModuleJob.run (node:internal/modules/esm/module_job:329:25)\n' +
    '    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:644:26)\n' +
    '    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:117:5)',
  cause: Error: cause
      at <anonymous> (/workspace/src/shared/logger.ts:62:51)
      at ModuleJob.run (node:internal/modules/esm/module_job:329:25)
      at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:644:26)
      at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:117:5),
  [Symbol(level)]: 'crit',
  [Symbol(splat)]: [
    Error: critError
        at <anonymous> (/workspace/src/shared/logger.ts:62:19)
        at ModuleJob.run (node:internal/modules/esm/module_job:329:25)
        at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:644:26)
        at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:117:5) {
      [cause]: Error: cause
          at <anonymous> (/workspace/src/shared/logger.ts:62:51)
          at ModuleJob.run (node:internal/modules/esm/module_job:329:25)
          at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:644:26)
          at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:117:5)
    }
  ],
  [Symbol(message)]: '{"cause":{},"level":"crit","message":"Critical error happened: critError","stack":"Error: critError\\n    at <anonymous> (/workspace/src/shared/logger.ts:62:19)\\n    at ModuleJob.run (node:internal/modules/esm/module_job:329:25)\\n    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:644:26)\\n    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:117:5)"}'
}

{
  error: Error: critError
      at <anonymous> (/workspace/src/shared/logger.ts:62:19)
      at ModuleJob.run (node:internal/modules/esm/module_job:329:25)
      at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:644:26)
      at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:117:5) {
    [cause]: Error: cause
        at <anonymous> (/workspace/src/shared/logger.ts:62:51)
        at ModuleJob.run (node:internal/modules/esm/module_job:329:25)
        at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:644:26)
        at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:117:5)
  },
  level: 'crit',
  message: 'Critical error happened:',
  [Symbol(level)]: 'crit',
  [Symbol(splat)]: [ { error: [Error] } ],
  [Symbol(message)]: '{"error":{},"level":"crit","message":"Critical error happened:"}'
}

{
  message: Error: critError
      at <anonymous> (/workspace/src/shared/logger.ts:62:19)
      at ModuleJob.run (node:internal/modules/esm/module_job:329:25)
      at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:644:26)
      at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:117:5) {
    [cause]: Error: cause
        at <anonymous> (/workspace/src/shared/logger.ts:62:51)
        at ModuleJob.run (node:internal/modules/esm/module_job:329:25)
        at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:644:26)
        at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:117:5)
  },
  level: 'crit',
  [Symbol(level)]: 'crit',
  [Symbol(message)]: '{"level":"crit","message":{}}'
}

{
  level: 'crit',
  [Symbol(level)]: 'crit',
  [Symbol(message)]: '{"level":"crit"}'
}

{
  level: 'crit',
  [Symbol(level)]: 'crit',
  [Symbol(message)]: '{"level":"crit"}'
}
```

Here are the conclusions : 

1. In the first case, `format.errors({ stack: true })` doesn't do anything. (Do note that, either way, the error's `message` was appended to the end of the `Critical error happened`.)
2. The second case is the same in terms of `format.errors({ stack: true })`'s impact, but this time, because the error was encapsulated inside an object its `message` wasn't appended.
3. The third case is the only one that has visible differences: 
   - When using `format.errors({ stack:true })`, it works as designed : the stack object is taken into account, the `message` is correct, but do note that `[Symbol(message)]` is now just the error's `message` and not a JSON `{ "level": "crit", "message": "critError" }` like the rest of the messages would be. Also, even though the `stack` property was added to the info object, it's not added to `[Symbol(message)]` so it won't be printed without explicitly saying so with `format.simple()` `format.json()`, `format.prettyPrint()` or `format.printf()`.
   - when you don't use `format.errors({ stack: true })`, the message will be of type Error, and will be printed as a `{}` by default (because of how `JSON.stringify()` works).
4. As for the fourth and fifth cases, which are essentially the same call, the Error seems to be lost into the void.

As the `errors` formatter does not seem to have a lot of impact, I won't be using it (mainly because I don't want to call my logging functions like the third option). Instead, I'll continue passing the options as metadata (like in the first or second cases), and print it nicely with a custom printf.
