### ISSUE TITLE
TypeError: Cannot read property 'error' of undefined

### ISSUE THREAD

**Issue by Kamshak** [winstonjs/logform#50]
Hey, 
running into this, used to work :( I have to say i'm getting a bit confused an it's become impossible to debug across so many packages

```
TypeError: Cannot read property 'error' of undefined
    at Colorizer.colorize (/home/valentin/repro/node_modules/logform/colorize.js:88:41)
    at Colorizer.transform (/home/valentin/repro/node_modules/logform/colorize.js:112:23)
    at Format.cascaded [as transform] (/home/valentin/repro/node_modules/logform/combine.js:34:24)
    at Console._write (/home/valentin/repro/node_modules/winston-transport/index.js:90:33)
    at doWrite (/home/valentin/repro/node_modules/winston-transport/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/home/valentin/repro/node_modules/winston-transport/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at Console.Writable.write (/home/valentin/repro/node_modules/winston-transport/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at DerivedLogger.ondata (/home/valentin/repro/node_modules/winston/node_modules/readable-stream/lib/_stream_readable.js:619:20)
    at emitOne (events.js:116:13)
    at DerivedLogger.emit (events.js:211:7)
    at addChunk (/home/valentin/repro/node_modules/winston/node_modules/readable-stream/lib/_stream_readable.js:291:12)
    at readableAddChunk (/home/valentin/repro/node_modules/winston/node_modules/readable-stream/lib/_stream_readable.js:278:11)
    at DerivedLogger.Readable.push (/home/valentin/repro/node_modules/winston/node_modules/readable-stream/lib/_stream_readable.js:245:10)
    at DerivedLogger.Transform.push (/home/valentin/repro/node_modules/winston/node_modules/readable-stream/lib/_stream_transform.js:148:32)
    at DerivedLogger._transform (/home/valentin/repro/node_modules/winston/lib/winston/logger.js:210:12)
    at DerivedLogger.Transform._read (/home/valentin/repro/node_modules/winston/node_modules/readable-stream/lib/_stream_transform.js:184:10
```

```ts
const alignedWithColorsAndTime = format.combine(
  format.colorize(),
  format.timestamp(),
  format.printf((info: any) => {
    let errStr = ''
    if (info.err) {
      errStr = `${getFullErrorStack(info.err)}`
    }

    const toPrint = Object.assign({}, info, {
      level: undefined,
      message: undefined
    })
    if (toPrint['err']) {
      toPrint['err'] = `${info.err.name}: ${info.err.message}`
    }

    const json = stringify(toPrint, null, 2)

    return `${info.timestamp} ${info.level}: ${info.message} ${json} ${errStr}`
  })
);

var logger: = winston.createLogger({
  level: process.env.LOG_LEVEL || 'info',
});

logger.add(
  new winston.transports.Console({
    format: alignedWithColorsAndTime,
    level: process.env.LOG_LEVEL || 'silly',
    colorize: true
  })
);
```

**Comment by Kamshak** [comment]
update logform if you get this :)
