### ISSUE TITLE
format.colorize() throws TypeError

### ISSUE THREAD

**Issue by ryanpage42** [winstonjs/logform#70]
Here's how I'm defining my format

```
        return format.combine(
            format.colorize(),
            format.timestamp({
                format: TIMESTAMP_PATTERN
            }),
            winston.format.simple(),
            format.printf(info => `[${info.timestamp}] ${info.level}: ${info.message}`)
        )
```
and it throws the following stack trace

```
TypeError: Cannot read property 'error' of undefined
    at Colorizer.colorize (/Users/ryan/git/p-nodejs/p-common/psp-logger/node_modules/logform/colorize.js:72:43)
    at Colorizer.transform (/Users/ryan/git/p-nodejs/p-common/psp-logger/node_modules/logform/colorize.js:94:28)
    at Format.info [as transform] (/Users/ryan/git/p-nodejs/p-common/psp-logger/node_modules/logform/combine.js:20:24)
```

When I remove the `format.colorize()` it logs fine. I am running MacOS Mojave. Going to try downgrading and see if there is any improvement.

**Comment by BigGillyStyle** [comment]
I'm also running Mojave as well as logform 2.1.1, and I believe I have a similar issue.  If I log `null`, I get:

```
TypeError: Cannot read property 'constructor' of null
    at [my-path]/node_modules/colors/lib/colors.js:108:34
    at Array.map (<anonymous>)
    at Function.applyStyle ([my-path]/node_modules/colors/lib/colors.js:107:18)
    at Object.builder ([my-path]/node_modules/colors/lib/colors.js:78:23)
    at Colorizer.colorize ([my-path]/node_modules/logform/colorize.js:73:49)
    at Colorizer.transform ([my-path]/node_modules/logform/colorize.js:102:27)
...
```

If I leave out `format.colorize({ all: true })` from my Winston configuration, I get no stack trace and a log message like:

`2019-03-14 01:24:58 warn: null`
