### ISSUE TITLE
TypeError: Cannot read property 'info' of undefined

### ISSUE THREAD

**Issue by hejkerooo** [winstonjs/logform#89]
Message:
```
 at Colorizer.colorize (/Users/krzysztofszostak/Documents/GitHub/sb-logger/node_modules/logform/colorize.js:72:43)
    at Colorizer.transform (/Users/krzysztofszostak/Documents/GitHub/sb-logger/node_modules/logform/colorize.js:98:25)
```

Winston: `3.1.0`
Logform: `2.1.2`

Anyone have any idea how to solve this issue?

**Comment by hejkerooo** [comment]
Package lock was keeping old version of logform

**Comment by rayfoss** [comment]
I was getting `ms is not a function` errors. Turns out my version of winston uses ^2.1.1 and log form made a braking API changing as a patch update to 2.1.2.
